name: Perl-Editor
version: 0.01
abstract: The Perl Refactoring Editor API
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  PPI: 0.993
  Module::Pluggable: 2.2
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
